### ISSUE TITLE
Weekly scrum - 13/11/23

### ISSUE THREAD

**Issue by slyflare** [access6080/MiniShopify#17]
Updates and developments for the week of 13/11/23.

**Comment by SaadEidGit** [comment]
I will be working on generating the UML diagram, database schema, and the CI badge to the ReadME.md.

**Comment by Meyiwa123** [comment]
I will be working on test cases for the customer entity and assisting in the development of the frontend.

**Comment by slyflare** [comment]
I finished creating the merchant model and its relevant functionality last week. Now I will focus on full testing it by creating relevant unit tests and integration tests.
