### ISSUE TITLE
Weekly scrum - 06/11/23

### ISSUE THREAD

**Issue by slyflare** [access6080/MiniShopify#6]
Updates and developments for the week of 06/11/23.

**Comment by slyflare** [comment]
Will be focused on creating the merchant model, service, and repository for the product.

**Comment by access6080** [comment]
For this week i work on creating the dtos, the mappers needed to map the dtos to entities and setting up the CI/CD to test and deploy code to azure.

**Comment by SaadEidGit** [comment]
For this week, I worked on creating the Cart, Store and Order models as well as the cart repository. I also included tests for all 3 tests.

**Comment by Meyiwa123** [comment]
For this week, I worked on the Merchant implementation. This includes creating the model, controller, repository and service.

**Comment by ajayitomisin** [comment]
For this week, I worked on the Product class and on creating a design for the front end.
